# Generated by Django 5.0.7 on 2024-07-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateUserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUT_first_name', models.CharField(max_length=100)),
                ('CUT_candidate_id', models.CharField(max_length=50, unique=True)),
                ('CUT_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], max_length=10, null=True)),
                ('CUT_display_summary', models.TextField(max_length=250)),
                ('CUT_years_of_experience', models.PositiveIntegerField()),
                ('CUT_location', models.CharField(max_length=100)),
                ('CUT_work_mode', models.CharField(max_length=50)),
                ('CUT_work_type', models.CharField(max_length=50)),
                ('CUT_hard_skills', models.TextField()),
                ('CUT_soft_skills', models.TextField()),
                ('CUT_tools', models.TextField()),
                ('CUT_experience', models.TextField()),
                ('CUT_educational', models.TextField()),
                ('CUT_certifications', models.TextField()),
                ('CUT_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RT_roles', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TT_tags', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTagTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTT_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidateusertable')),
                ('CRT_tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.tagstable')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRoleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRT_userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidateusertable')),
                ('CRT_roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.rolestable')),
            ],
        ),
        migrations.AddField(
            model_name='candidateusertable',
            name='CUT_roles',
            field=models.ManyToManyField(through='Candidate.CandidateRoleTable', to='Candidate.rolestable'),
        ),
        migrations.AddField(
            model_name='candidateusertable',
            name='CUT_tags',
            field=models.ManyToManyField(through='Candidate.CandidateTagTable', to='Candidate.tagstable'),
        ),
    ]
